#!/bin/bash -login
#SBATCH --nodes=1
#SBATCH --partition veryshort
#SBATCH --job-name=promptchange
#SBATCH --time 04:00:00
#SBATCH --account=COSC027924
#SBATCH --output prompt.out

#module load CUDA
#module load tools/git/2.35.1

#export LOCAL_RANK=0
source ~/.bashrc
conda activate

cd $SLURM_SUBMIT_DIR
#python3 ~/scratch/EgoVLP-main/run/test_epic.py
python3 ~/scratch/EgoVLP-main/change_prompt.py
